# Generated by Django 4.2.5 on 2023-09-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_photographer_photographerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographerprofile',
            old_name='Photographer',
            new_name='photographer',
        ),
    ]
